# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'AgoraHumming-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'AgoraRtcEngine_Special_iOS', '4.1.1.15'
  pod 'RTMTokenBuilder', '1.0.1'
  pod 'AgoraHummingService', :path => "binary/AgoraHummingService_Binary.podspec"
end
